export const FETCH_LAUNCHES_REQUEST = "FETCH_LAUNCHES_REQUEST";
export const FETCH_LAUNCHES_SUCCESS = "FETCH_LAUNCHES_SUCCESS";
export const FETCH_LAUNCHES_FAILURE = "FETCH_LAUNCHES_FAILURE";

export const SHOW_SNACKBAR_NOTIFICATION = "SHOW_SNACKBAR_NOTIFICATION";
export const HIDE_SNACKBAR_NOTIFICATION = "HIDE_SNACKBAR_NOTIFICATION";
